# Generated by Django 5.2.5 on 2026-03-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='classification',
            field=models.CharField(blank=True, default='G2G', help_text='Classification (e.g., G2G, G2C)', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, help_text='Expected processing time (e.g., 20 minutes)', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.CharField(choices=[('internal', 'Internal Services'), ('external', 'External Services')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='transaction_type',
            field=models.CharField(choices=[('simple', 'Simple Transaction'), ('complex', 'Complex Transaction'), ('highly_technical', 'Highly Technical Transaction')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='where_to_secure',
            field=models.CharField(blank=True, help_text='Office or Unit where the service is secured', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='who_may_avail',
            field=models.CharField(blank=True, help_text='Target constituents (e.g., UP System Employees)', max_length=300),
        ),
    ]
