# Generated by Django 5.2.5 on 2026-03-11 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_service_classification_service_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Content status in the publishing workflow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Short title for the image.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Context or descriptive caption for the image.')),
                ('image_file', models.ImageField(upload_to='media_gallery/')),
                ('published_date', models.DateField(help_text='Date the event or subject occurred.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Gallery Item',
                'verbose_name_plural': 'Media Gallery Items',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
