# Generated by Django 5.2.5 on 2026-03-11 05:45

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_mediagallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Content status in the publishing workflow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('sspmo', 'SSPMO'), ('shrdo', 'SHRDO'), ('sco', 'SCO'), ('ovpa-qms', 'OVPA-QMS'), ('special', 'Special Projects')], default='special', max_length=20)),
                ('excerpt', models.TextField(help_text='Short summary for the project card.')),
                ('content', ckeditor.fields.RichTextField(help_text='Full article content and design.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
