# Generated by Django 5.2.5 on 2026-03-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuance',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='officestructure',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officestructure',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='page',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='service',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.'),
        ),
    ]
