# Generated by Django 6.1 on 2026-08-13 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_contactinquiry_options_alter_feedback_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Content status in the publishing workflow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(help_text='Advisory text to display in the running ticker', max_length=300)),
                ('category', models.CharField(choices=[('notice', 'Admin Notice'), ('workshop', 'Workshop / Event'), ('maintenance', 'System Maintenance'), ('emergency', 'Emergency / Suspension'), ('general', 'General Advisory')], default='notice', max_length=30)),
                ('link_url', models.CharField(blank=True, help_text='Optional target link URL (e.g., /resources/issuances/)', max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set active to include in the ticker bar')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which advisories appear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advisory Ticker Item',
                'verbose_name_plural': 'Advisory Ticker Items',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
