# Generated by Django 6.1 on 2026-08-24 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_advisoryticker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimableCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Content status in the publishing workflow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payee_name', models.CharField(db_index=True, help_text='Supplier, Company, or Individual Payee Name', max_length=255)),
                ('voucher_number', models.CharField(db_index=True, help_text='Disbursement Voucher (DV) Number', max_length=100)),
                ('check_number', models.CharField(blank=True, help_text='Check or ADA Reference Number', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in PHP', max_digits=12)),
                ('check_date', models.DateField(help_text='Date of Check / Voucher')),
                ('claim_status', models.CharField(choices=[('ready', 'Ready for Pick-up / Release'), ('processing', 'Processing / In Audit'), ('released', 'Released / Claimed'), ('cancelled', 'Stale / Cancelled')], default='ready', max_length=20)),
                ('date_released', models.DateField(blank=True, help_text='Date when check was claimed/released', null=True)),
                ('claiming_requirements', models.TextField(default='1. Official Receipt / Sales Invoice\n2. Two (2) Valid Government-issued IDs\n3. Authorization Letter or SPA (if representative)', help_text='Mandatory documents required upon claiming')),
                ('remarks', models.TextField(blank=True, help_text='Notes for supplier or releasing cashier', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claimable Check',
                'verbose_name_plural': 'Claimable Checks',
                'ordering': ['-check_date', 'payee_name'],
            },
        ),
    ]
