# Generated by Django 6.1 on 2026-08-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_claimablecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimablecheck',
            name='pin_code',
            field=models.CharField(blank=True, help_text='6-digit security PIN for supplier authorization to unlock check amount and details.', max_length=10),
        ),
    ]
