# Generated by Django 6.1 on 2026-08-24 04:15

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_claimablecheck_pin_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOfficePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Content status in the publishing workflow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='If checked, content is archived and hidden from the public site.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hero_title', models.CharField(default='System Cash Office (SCO)', max_length=200)),
                ('hero_subtitle', models.TextField(default='Managing financial collections, cash disbursements, electronic payment processing, and supplier check releases across the University of the Philippines System.')),
                ('cashier_hours', models.CharField(default='Mon - Fri: 8:00 AM - 4:00 PM', max_length=150)),
                ('office_location', models.CharField(default='2nd Floor, Quezon Hall, UP Diliman', max_length=200)),
                ('releasing_phone', models.CharField(default='(02) 8981-8500 loc. 2524 / 2525', max_length=150)),
                ('contact_email', models.EmailField(default='cashoffice.system@up.edu.ph', max_length=254)),
                ('mandate_title', models.CharField(default='Fiscal Responsibility & Cashiering Excellence', max_length=200)),
                ('mandate_content', ckeditor.fields.RichTextField(default='The System Cash Office (SCO) operates under the direct supervision of the Office of the Vice President for Administration. It safeguards University monetary assets, enforces strict treasury governance according to Commission on Audit (COA) standards, and maintains transparent, accessible payment systems for suppliers, personnel, and students.')),
                ('window_1_desc', models.TextField(default='Tuition fees, transcript fees, administrative clearances, dorm payments, and general university receipts.', help_text='Window 1: Official Collections')),
                ('window_2_desc', models.TextField(default='Disbursement checks and ADA notices for suppliers, contractors, and corporate vendors.', help_text='Window 2: Supplier Check Releasing')),
                ('window_3_desc', models.TextField(default='Faculty & staff payroll checks, overload honoraria, research stipends, and student assistant allowances.', help_text='Window 3: Payroll & Honoraria')),
                ('window_4_desc', models.TextField(default='Official travel cash advances, project fund liquidations, and petty cash replenishings.', help_text='Window 4: Special Cash Advances')),
                ('claiming_guidelines', ckeditor.fields.RichTextField(default='To ensure smooth verification and prevent authorization delays, please bring mandatory documents (Official Receipt, 2 Valid IDs, SPA) when claiming at Window 2.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Office Page Content',
                'verbose_name_plural': 'Cash Office Page Content',
            },
        ),
    ]
