# Generated by Django 6.1 on 2026-08-24 04:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_cashofficepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashofficepage',
            name='bor_history_content',
            field=ckeditor.fields.RichTextField(default='<p>The UP-System Cash Office (SCO) was formally created at the <strong>1144th Meeting of the Board of Regents (BOR) on 31 August 2000</strong> via Executive Order, becoming operational on May 5, 2001. Guided by the New Government Accounting System (NGAS) and Commission on Audit (COA) standards under the Office of the Vice President for Administration (OVPA), SCO manages financial disbursements, electronic transfers, and official collections across all UP System offices and Constituent Universities (CUs).</p>'),
        ),
        migrations.AddField(
            model_name='cashofficepage',
            name='bor_history_title',
            field=models.CharField(default='BOR Executive Creation & NGAS Governance', max_length=200),
        ),
        migrations.AddField(
            model_name='cashofficepage',
            name='check_process_flow',
            field=ckeditor.fields.RichTextField(default='<ol><li><strong>DV Review & Check Preparation</strong>: Audit DVs for fund code, payee name, and approved supporting documents.</li><li><strong>Check Printing & Signing</strong>: Print check and register in Check Register. Counter-signed by SCO Chief and VPA.</li><li><strong>Vault Safekeeping</strong>: Store securely in Cashier Vault pending release.</li><li><strong>Window 2 Release</strong>: Release to Payee/Authorized Representative upon receipt of BIR OR/Sales Invoice and 2 valid IDs.</li></ol>'),
        ),
        migrations.AddField(
            model_name='cashofficepage',
            name='citizens_charter_summary',
            field=ckeditor.fields.RichTextField(default="<p>Under the UP System Citizen's Charter, SCO operates from <strong>Monday to Friday, 8:00 AM to 5:00 PM (No Noon Break)</strong> with standard service targets:</p><ul><li><strong>Official Collections & OR Issuance</strong>: 8 Minutes Target Turnaround</li><li><strong>Check & RDA Release</strong>: 10 Minutes Target Turnaround</li></ul>"),
        ),
        migrations.AddField(
            model_name='cashofficepage',
            name='rda_process_flow',
            field=ckeditor.fields.RichTextField(default='<ol><li><strong>DV Receipt & Verification</strong>: Receive approved DVs from System Accounting Office (UPSAO).</li><li><strong>WeAccess Encoding</strong>: Review name, bank account number, amount, and fund code. Encode into Landbank WeAccess.</li><li><strong>SCO Chief Review</strong>: Verify accuracy and counter-sign.</li><li><strong>VPA Executive Approval</strong>: Forward to Vice President for Administration for final signature and digital bank dispatch.</li></ol>'),
        ),
        migrations.AddField(
            model_name='cashofficepage',
            name='receivable_process_flow',
            field=ckeditor.fields.RichTextField(default='<ol><li><strong>Order of Payment</strong>: Client presents Order of Payment from issuing unit.</li><li><strong>Payment Remittance & Verification</strong>: Cashier validates documents and receives payment (cash, check, or bank transfer).</li><li><strong>OR Issuance & Daily Deposit</strong>: Issue Official Receipt (OR) in 5 minutes and deposit collections daily to authorized government depository bank.</li></ol>'),
        ),
        migrations.AddField(
            model_name='cashofficepage',
            name='voip_extensions',
            field=models.CharField(default='VOIP: 2618 / 2540 / 2524 / 2525', max_length=200),
        ),
        migrations.AlterField(
            model_name='cashofficepage',
            name='office_location',
            field=models.CharField(default='SFAB Building, Magsaysay rd. cor Agoncillo, UP Diliman Campus, Quezon City', max_length=200),
        ),
    ]
